import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

export const metadata = {
  title: "Terms of Use",
};

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-2xl px-4 py-10 sm:py-14">
      <BrandLogo href="/" showTagline={false} />

      <h1 className="mt-8 text-3xl font-extrabold text-white">Terms of Use</h1>
      <p className="mt-2 text-sm text-zinc-500">Last updated: July 9, 2026</p>

      <div className="mt-6 space-y-6 text-sm leading-7 text-zinc-300">
        <section>
          <h2 className="font-bold text-white">1. Acceptance</h2>
          <p className="mt-2">
            By creating an Errday account or using the service at errday.ch you
            agree to these terms. If you do not agree, please do not use Errday.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">2. What Errday is</h2>
          <p className="mt-2">
            Errday is a personal health tracking tool for training, nutrition,
            sleep and reflection. It is provided free of charge for your own
            private use.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">3. Not medical advice</h2>
          <p className="mt-2">
            Errday does not provide medical advice, diagnosis or treatment.
            Calorie, macro, recovery and other figures are estimates, not
            measurements. Always consult a qualified professional for health
            decisions, and never disregard professional advice because of
            something you saw in Errday. For eating disorders, injuries,
            medication questions or emergencies, seek qualified help.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">4. AI estimates</h2>
          <p className="mt-2">
            Food photo, label and text estimates are generated by AI and are
            approximate by nature. Review them before relying on them — portion
            sizes, hidden ingredients and cooking methods can change the real
            values significantly.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">5. Your account</h2>
          <p className="mt-2">
            Keep your password and any sync keys private — you are responsible
            for activity under your account. An account is for a single person.
            Tell us promptly if you suspect unauthorized access.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">6. Acceptable use</h2>
          <p className="mt-2">
            Don&apos;t use Errday for anything unlawful, don&apos;t try to break,
            overload, scrape or reverse-engineer the service, and don&apos;t
            attempt to access other users&apos; data.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">7. Your data</h2>
          <p className="mt-2">
            The entries you create are yours. You can edit or delete most of
            them in the app at any time, and request full deletion by email. How
            we handle your data is described in the{" "}
            <Link className="font-semibold text-[var(--accent)]" href="/privacy">
              privacy policy
            </Link>
            .
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">8. Availability</h2>
          <p className="mt-2">
            Errday is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;.
            As a free service it may change, be interrupted for maintenance, or
            be discontinued, and features may be added or removed without notice.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">9. Liability</h2>
          <p className="mt-2">
            To the extent permitted by Swiss law, the operator is not liable for
            indirect or consequential damages, or for any loss arising from
            reliance on estimates or from unavailability of the service. Nothing
            in these terms limits liability that cannot be limited by law.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">10. Changes</h2>
          <p className="mt-2">
            We may update these terms as Errday evolves. Continued use after a
            change means you accept the updated terms; the date above shows the
            latest version.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">11. Termination</h2>
          <p className="mt-2">
            You can stop using Errday and delete your account at any time. We may
            suspend or remove an account that abuses the service or breaks these
            terms.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-white">12. Governing law</h2>
          <p className="mt-2">
            Swiss law applies. Place of jurisdiction is Switzerland.
          </p>
        </section>
      </div>

      <p className="mt-10 text-sm">
        <Link className="font-semibold text-[var(--accent)]" href="/privacy">
          Privacy policy
        </Link>
        <span className="mx-2 text-zinc-600">·</span>
        <Link className="font-semibold text-[var(--accent)]" href="/imprint">
          Legal notice
        </Link>
        <span className="mx-2 text-zinc-600">·</span>
        <Link className="font-semibold text-[var(--accent)]" href="/login">
          Back to Errday
        </Link>
      </p>
    </div>
  );
}
